#!/bin/bash

# Replaces markdown text on the pasteboard with rich text formatted html.

hex=$(pbpaste | \
    /usr/local/bin/pandoc -t html -s --highlight-style pygments | \
    hexdump -ve '1/1 "%.2x"')
osascript -e "set the clipboard to «data HTML${hex}»"
